Lab10 Call secondary workflow
Each workflow is a snippet of work. You can chain them together.

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -113,3 +113,16 @@ jobs:
      - shell: bash
        run: |
            echo argument count is ${{ steps.report-count.outputs.arg-count }} 
+           # force failure to throw create issue on failure in lab 10
+           exit 1
+           
+  # lab 10
+  create-issue-on-failure:
+   permissions:
+     issues: write
+   needs: [test-run, count-args]
+   if: always() && failure()
+   uses: ./.github/workflows/create-failure-issue.yml
+   with:
+     title: "Automated workflow failure issue for commit ${{ github.sha }}"
+     body: "This issue was automatically created by the GitHub Action workflow ** ${{github.workflow }} **"
